version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - x-network


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00000
      POSTGRES_DB: demo
    ports:
      - "5433:5432"
    networks:
      - x-network

networks:
  x-network:
    driver: bridge